version: '3.4'

services:
  company:
    working_dir: /amos
    build: 
      dockerfile: company.Dockerfile
    ports:
      - "19193:19193"

  tax_advisor:
    working_dir: /amos
    build: 
      dockerfile: tax_advisor.Dockerfile
    ports:
      - "29193:29193"

  bank:
    working_dir: /amos
    build: 
      dockerfile: bank.Dockerfile
    ports:
      - "39193:39193"

  app:
    working_dir: /home/node/app
    build: 
      dockerfile: frontend_socket/international-dataspace-station/app.Dockerfile
    ports:
      - "3000:3000"