version: '3.4'

services:
  company_connector:
    build: 
      dockerfile: company_connector.Dockerfile
    ports:
      - "19193:19193"

  tax_advisor_connector:
    build: 
      dockerfile: tax_advisor_connector.Dockerfile
    ports:
      - "29193:29193"

  bank_connector:
    build: 
      dockerfile: bank_connector.Dockerfile
    ports:
      - "39193:39193"

  company_frontend:
    build:
      context: frontend_socket/international-dataspace-station
      dockerfile: company_frontend.Dockerfile
    ports:
      - "3001:3000"

  tax_advisor_frontend:
    build:
      context: frontend_socket/international-dataspace-station
      dockerfile: tax_advisor_frontend.Dockerfile
    ports:
      - "3002:3000"

  bank_frontend:
    build:
      context: frontend_socket/international-dataspace-station
      dockerfile: bank_frontend.Dockerfile
    ports:
      - "3003:3000"