version: '3.4'

services:
  company:
    build:
      context: edc-connector
    environment:
      - EDC_CONFIG=resources/configuration/company-configuration.properties
    profiles:
      - company
      - complete
    ports:
      - "19191:19191"
      - "19192:19192"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"

  taxadvisor:
    build:
      context: edc-connector
    environment:
      - EDC_CONFIG=resources/configuration/tax_advisor-configuration.properties
    profiles:
      - taxadvisor
      - complete
    ports:
      - "29191:19191"
      - "29192:19192"
      - "29193:19193"
      - "29194:19194"
      - "29291:19291"

  bank:
    build:
      context: edc-connector
    environment:
      - EDC_CONFIG=resources/configuration/bank-configuration.properties
    profiles:
      - bank
      - complete
    ports:
      - "39191:19191"
      - "39192:19192"
      - "39193:19193"
      - "39194:19194"
      - "39291:19291"

  company-frontend:
    build:
      context: frontend
    environment:
      - NEXT_PUBLIC_CONNECTOR_NAME=company
    profiles:
      - company
      - complete
    ports:
      - "3001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  taxadvisor-frontend:
    build:
      context: frontend
    environment:
      - NEXT_PUBLIC_CONNECTOR_NAME=taxadvisor
    profiles:
      - taxadvisor
      - complete
    ports:
      - "3002:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  bank-frontend:
    build:
      context: frontend
    environment:
      - NEXT_PUBLIC_CONNECTOR_NAME=bank
    profiles:
      - bank
      - complete
    ports:
      - "3003:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  company-database:
    build:
      context: database
    environment:
      - CONNECTOR_NAME=company
    profiles:
      - company
      - complete
    ports:
      - "8081:8080"

  taxadvisor-database:
    build:
      context: database
    environment:
      - CONNECTOR_NAME=taxadvisor
    profiles:
      - taxadvisor
      - complete
    ports:
      - "8082:8080"

  bank-database:
    build:
      context: database
    environment:
      - CONNECTOR_NAME=bank
    profiles:
      - bank
      - complete
    ports:
      - "8083:8080"