version: '3.4'

services:
  company:
    build:
      context: edc-connector
      dockerfile: company_connector.Dockerfile
    ports:
      - "19191:19191"
      - "19192:19192"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"

  taxadvisor:
    build:
      context: edc-connector
      dockerfile: tax_advisor_connector.Dockerfile
    ports:
      - "29191:19191"
      - "29192:19192"
      - "29193:19193"
      - "29194:19194"
      - "29291:19291"

  bank:
    build:
      context: edc-connector
      dockerfile: bank_connector.Dockerfile
    ports:
      - "39191:19191"
      - "39192:19192"
      - "39193:19193"
      - "39194:19194"
      - "39291:19291"

  company_frontend:
    build:
      context: frontend
      dockerfile: company_frontend.Dockerfile
    ports:
      - "3001:3000"

  tax_advisor_frontend:
    build:
      context: frontend
      dockerfile: tax_advisor_frontend.Dockerfile
    ports:
      - "3002:3000"

  bank_frontend:
    build:
      context: frontend
      dockerfile: bank_frontend.Dockerfile
    ports:
      - "3003:3000"