version: '3.4'

services:
  company:
    working_dir: /amos
    build: 
      dockerfile: company_connector.Dockerfile
    ports:
      - "19191:19191"
      - "19192:19192"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"

  taxadvisor:
    working_dir: /amos
    build: 
      dockerfile: tax_advisor_connector.Dockerfile
    ports:
      - "29191:19191"
      - "29192:19192"
      - "29193:19193"
      - "29194:19194"
      - "29291:19291"

  bank:
    working_dir: /amos
    build: 
      dockerfile: bank_connector.Dockerfile
    ports:
      - "39191:19191"
      - "39192:19192"
      - "39193:19193"
      - "39194:19194"
      - "39291:19291"

  company_frontend:
    working_dir: /amos
    build:
      dockerfile: frontend_socket/international-dataspace-station/company_frontend.Dockerfile
    ports:
      - "3001:3001"

  tax_advisor_frontend:
    working_dir: /amos
    build:
      dockerfile: frontend_socket/international-dataspace-station/tax_advisor_frontend.Dockerfile
    ports:
      - "3002:3002"

  bank_frontend:
    working_dir: /amos
    build:
      dockerfile: frontend_socket/international-dataspace-station/bank_frontend.Dockerfile
    ports:
      - "3003:3003"