version: '3.4'

services:
  company:
    working_dir: /amos
    build: 
      dockerfile: company.Dockerfile
    ports:
      - "19191:19191"

  tax_advisor:
    working_dir: /amos
    build: 
      dockerfile: tax_advisor.Dockerfile
    ports:
      - "29191:29191"

  bank:
    working_dir: /amos
    build: 
      dockerfile: bank.Dockerfile
    ports:
      - "39191:39191"

  app:
    working_dir: /home/node/app
    build: 
      dockerfile: frontend_socket/international-dataspace-station/app.Dockerfile
    ports:
      - "3000:3000"