version: '3.4'

services:

  company:
    container_name: company
    build: 
      dockerfile: company.Dockerfile
    ports:
      - "19191:19191"
      - "19192:19192"
      - "19193:19193"
      - "19194:19194"
      - "19195:7171"
      - "19291:19291"

  tax_advisor:
    container_name: tax_advisor
    build: 
      dockerfile: tax_advisor.Dockerfile
    ports:
      - "29191:29191"
      - "29192:29192"
      - "29193:29193"
      - "29194:29194"
      - "29195:7171"
      - "29291:29291"

  bank:
    container_name: bank
    build: 
      dockerfile: bank.Dockerfile
    ports:
      - "39191:39191"
      - "39192:39192"
      - "39193:39193"
      - "39194:39194"
      - "39195:7171"
      - "39291:39291"

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    environment:
      AZURITE_ACCOUNTS: taxadvisorassets:key1;companyassets:key2;bankassets:key3

  registration-service:
    container_name: registration-service
    build:
      dockerfile: registration_service.Dockerfile
    ports:
      - "8181:8181"
      - "8184:8184"
      - "5008:5008"
      - "7171:7171"

  did-server:
    container_name: did-server
    image: nginx
    volumes:
      - ./participants/did-server:/usr/share/nginx/html
    ports:
      - "7070:80"

  cli-registration:
    container_name: cli-registration
    build:
      dockerfile: cli.Dockerfile
    depends_on:
      bank:
        condition: service_healthy
      company:
        condition: service_healthy
      tax_advisor:
        condition: service_healthy
    