name: Create and publish a bank connector and frontend

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image-connector:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_connector
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            com.example.service=bank_connector
            com.example.version={{version}}

      - name: Build and push Docker image
	      id: push
	      working-directory: ./src
        run: |
          docker-compose build bank
          docker tag ${{ env.IMAGE_NAME }}_bank:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_connector:${{ steps.meta.outputs.tags }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_connector:${{ steps.meta.outputs.tags }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_connector
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  build-and-push-image-database:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_database
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            com.example.service=bank_database
            com.example.version={{version}}

      - name: Build and push Docker image
	      id: push
	      working-directory: ./src
        run: |
          docker-compose build bank-database
          docker tag ${{ env.IMAGE_NAME }}_bank-database:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_database:${{ steps.meta.outputs.tags }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_database:${{ steps.meta.outputs.tags }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_database
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  build-and-push-image-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_frontend
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            com.example.service=bank_frontend
            com.example.version={{version}}

      - name: Build and push Docker image
	      id: push
	      working-directory: ./src
        run: |
          docker-compose build bank-frontend
          docker tag ${{ env.IMAGE_NAME }}_bank-frontend:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_frontend:${{ steps.meta.outputs.tags }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_frontend:${{ steps.meta.outputs.tags }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bank_frontend
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
